apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-init-script
  namespace: ollama-system
data:
  init-ollama.sh: |
    #!/bin/bash
    set -e
    
    echo "=== INIT CONTAINER: Starting model download ==="
    
    # Start Ollama server in background temporarily  
    echo "Starting temporary Ollama server..."
    /bin/ollama serve &
    OLLAMA_PID=\$!
    echo "Ollama PID: \$OLLAMA_PID"
    
    # Wait for Ollama to be ready
    echo "Waiting for Ollama API to be ready..."
    for i in {1..30}; do
        if curl -s http://localhost:11434/api/version >/dev/null 2>&1; then
            echo "Ollama API is ready!"
            break
        fi
        echo "Waiting... (\$i/30)"
        sleep 2
    done
    
    # Pull the model
    echo "Pulling qwen2:0.5b model (small and reliable)..."
    if /bin/ollama pull qwen2:0.5b; then
        echo "✅ Model qwen2:0.5b downloaded successfully!"
    else
        echo "❌ Failed to download model"
        pkill -f ollama || true
        exit 1
    fi
    
    # Clean shutdown - handle all edge cases
    echo "Shutting down temporary Ollama server..."
    
    # Try killing by PID if it exists
    if [[ -n "\$OLLAMA_PID" ]] && kill -0 "\$OLLAMA_PID" 2>/dev/null; then
        echo "Killing Ollama process \$OLLAMA_PID"
        kill "\$OLLAMA_PID" 2>/dev/null || true
        sleep 2
    fi
    
    # Fallback - kill any ollama processes
    pkill -f "ollama serve" 2>/dev/null || true
    sleep 1
    
    echo "=== INIT CONTAINER: Completed successfully ==="
    exit 0