apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama-system
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      initContainers:
      - name: model-puller
        image: ollama/ollama:latest
        command: ["/bin/bash", "-c"]
        args: ["/scripts/init-ollama.sh"]
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0:11434"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        - name: init-script
          mountPath: /scripts
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
          limits:
            memory: "8Gi"
            cpu: "8"
      containers:
      - name: ollama
        image: ollama/ollama:0.11.11
        ports:
        - containerPort: 11434
          name: http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0:11434"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"
            # nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "8"
            # nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-pvc
      - name: init-script
        configMap:
          name: ollama-init-script
          defaultMode: 0755