apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: ollama-system
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service:11434"
        - name: WEBUI_SECRET_KEY
          value: "AAAAC3NzaC1lZDI1NTE5AAAAIIx6qu3/y0p4H5vB9jhHU4FdCfj7M8Ckp4D4kjcVFfv2"
        - name: WEBUI_AUTH
          value: "False"  # Disable auth for simplicity - change to "True" for production
        volumeMounts:
        - name: webui-data
          mountPath: /app/backend/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: webui-data
        persistentVolumeClaim:
          claimName: open-webui-pvc